victoire_core:
    widgets:
        Form:
            class: "Victoire\\Widget\\FormBundle\\Entity\\WidgetForm"
            name: Form
jms_translation:
    configs:
        victoire_form_bundle:
            dirs: ["@VictoireFormBundle"]
            output_dir: "@VictoireFormBundle/Resources/translations"
