services:
    victoire_core.widget_form_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        class: Victoire\Widget\FormBundle\Resolver\WidgetFormContentResolver
        arguments:
            - '@victoire.form_widget.domain.captcha.handler'
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Form }

    #alias to the entity
    victoire.widget.form:
        class: Victoire\Widget\FormBundle\Entity\WidgetForm

    #alias to the form
    victoire.widget.form.form:
        class: Victoire\Widget\FormBundle\Form\WidgetFormType
        arguments:
            - %victoire_widget_form.prefill%
            - '@victoire.form_widget.domain.captcha.handler'
        tags:
            - { name: form.type }

    victoire.form_widget.helper.recaptcha:
      class: Victoire\Widget\FormBundle\Helper\RecaptchaHelper
      arguments:
          - '%victoire_widget_form.recaptcha_public_key%'
          - '%victoire_widget_form.recaptcha_private_key%'

    victoire.form_widget.twig.extension:
        class: Victoire\Widget\FormBundle\Twig\WidgetFormExtension
        tags:
            - { name: twig.extension }

    # Domain

    victoire.form_widget.domain.captcha.handler:
      class: Victoire\Widget\FormBundle\Domain\Captcha\CaptchaHandler
      arguments:
          -  !tagged victoire.form_widget.captcha.adapter
          - '@translator'

    victoire.form_widget.domain.captcha.adapter.recaptcha:
      class: Victoire\Widget\FormBundle\Domain\Captcha\Adapter\RecaptchaAdapter
      arguments:
          - '%victoire_widget_form.recaptcha_private_key%'
          - '%victoire_widget_form.recaptcha_public_key%'
      tags:
          - 'victoire.form_widget.captcha.adapter'
